Models/Cart.cs
using System;
namespace HarmonyHaven.Models
{
	public class Cart
	{   
            public int Id { get; set; }
            public decimal CartTotal { get; set; }
            public List<CartItem> CartItems { get; set; }
       
    }

}

Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HarmonyHaven.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HarmonyHaven.Controllers
{
    public class CartsController : Controller
    {
        private readonly ApplicationContext Context;

        public CartsController(ApplicationContext _context)
        {
            Context = _context;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult AddToCart(int id)
        {
            Product CurrentProduct = Context.Products.FirstOrDefault(x => x.Id == id);
            CartItem ExistingCartItem = Context.CartItems
                .FirstOrDefault(x => x.CartId == 1 && x.ProductId == CurrentProduct.Id);
            if (ExistingCartItem != null)
            {
                ExistingCartItem.Quantity = ExistingCartItem.Quantity + 1;
                ExistingCartItem.CartItemTotal = ExistingCartItem.CartItemTotal + CurrentProduct.ProductPrice;
                Context.CartItems.Update(ExistingCartItem);
                Cart Cart = Context.Carts.FirstOrDefault(x => x.Id == 1);
                Cart.CartTotal = Cart.CartTotal + CurrentProduct.ProductPrice;
                Context.SaveChanges();
            }
            else
            {
                CartItem CartItem = new CartItem();
                CartItem.ProductId = CurrentProduct.Id;
                CartItem.Quantity = 1;
                CartItem.CartItemTotal = CurrentProduct.ProductPrice;
                Cart Cart = Context.Carts.FirstOrDefault(x => x.Id == 1);
                Cart.CartTotal = Cart.CartTotal + CartItem.CartItemTotal;
                Cart.CartItems = new List<CartItem>();
                Cart.CartItems.Add(CartItem);
                Context.Carts.Update(Cart);
                Context.SaveChanges();
            }

            return RedirectToAction(nameof(Details));

        }
        public IActionResult AddOneItem(int id)
        {
            Cart ThisCart = Context.Carts.FirstOrDefault(x => x.Id == 1);
            Product CurrentProduct = Context.Products.FirstOrDefault(x => x.Id == id);
            CartItem CurrentCartItem = Context.CartItems
                .FirstOrDefault(x => x.CartId == 1 && x.ProductId == id);

            CurrentCartItem.Quantity = CurrentCartItem.Quantity + 1;
            CurrentCartItem.CartItemTotal = CurrentCartItem.CartItemTotal + CurrentProduct.ProductPrice;
            Context.CartItems.Update(CurrentCartItem);
            ThisCart.CartTotal = ThisCart.CartTotal + CurrentProduct.ProductPrice;
            Context.Carts.Update(ThisCart);
            Context.SaveChanges();

            return RedirectToAction(nameof(Details));

        }

        public IActionResult RemoveOneItem(int id)

        {

            Cart ThisCart = Context.Carts.FirstOrDefault(x => x.Id == 1);
            Product CurrentProduct = Context.Products.FirstOrDefault(x => x.Id == id);
            CartItem CurrentCartItem = Context.CartItems
                .FirstOrDefault(x => x.CartId == 1 && x.ProductId == id);


            if (CurrentCartItem != null)
            {
                if (CurrentCartItem.Quantity > 1)

                {
                    CurrentCartItem.Quantity = CurrentCartItem.Quantity - 1;
                    CurrentCartItem.CartItemTotal = CurrentCartItem.CartItemTotal - CurrentProduct.ProductPrice;
                    Context.CartItems.Update(CurrentCartItem);
                    ThisCart.CartTotal = ThisCart.CartTotal - CurrentProduct.ProductPrice;
                    Context.Carts.Update(ThisCart);
                    Context.SaveChanges();
                }

                else if (CurrentCartItem.Quantity <= 1)

                {
                    CurrentCartItem.Quantity = 0;
                    Context.CartItems.Remove(CurrentCartItem);
                    ThisCart.CartTotal = ThisCart.CartTotal - CurrentProduct.ProductPrice;
                    Context.Carts.Update(ThisCart);
                    Context.SaveChanges();
                }
            }

            return RedirectToAction(nameof(Details));
        }
        public IActionResult RemoveAllOfTheseItems(int id)
        {

            Cart ThisCart = Context.Carts.FirstOrDefault(x => x.Id == 1);
            Product CurrentProduct = Context.Products.FirstOrDefault(x => x.Id == id);
            CartItem CurrentCartItem = Context.CartItems
                .FirstOrDefault(x => x.CartId == 1 && x.ProductId == id);
            List<CartItem> AllOfTheseItems = Context.CartItems.ToList();

            foreach (CartItem item in AllOfTheseItems.Where(x => x.ProductId == id))

            {
                ThisCart.CartTotal = ThisCart.CartTotal - (CurrentProduct.ProductPrice * CurrentCartItem.Quantity);
                CurrentCartItem.Quantity = CurrentCartItem.Quantity - 1;
                Context.CartItems.Remove(item);
                Context.Carts.Update(ThisCart);
            }
            Context.SaveChanges();
            return RedirectToAction(nameof(Details));
        }

        public IActionResult EmptyCart(int id)
        {
            List<CartItem> CurrentCartItem = Context.CartItems
                .Where(x => x.Id >= 1).ToList();
            Context.CartItems.RemoveRange(CurrentCartItem);

            Cart ThisCart = Context.Carts.FirstOrDefault(x => x.Id == 1);
            ThisCart.CartTotal = 0;
            Context.Carts.Update(ThisCart);
            Context.SaveChanges();
            return RedirectToAction(nameof(Details));
        }
        public IActionResult Details()
        {
            Cart Cart = Context.Carts
                .Include(ci => ci.CartItems).ThenInclude(p => p.Product).FirstOrDefault(x => x.Id == 1);
            return View(Cart);
        }


        public IActionResult DetailsSek()
        {
            Cart Cart = Context.Carts
                .Include(ci => ci.CartItems).ThenInclude(p => p.Product).FirstOrDefault(x => x.Id == 1);

            foreach (CartItem cartItem in Cart.CartItems)
            {
                cartItem.CartItemTotal /= 10;
            }
            Cart.CartTotal /= 10;


            return View(Cart);
        }

    }
}

Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HarmonyHaven.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HarmonyHaven.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ApplicationContext Context;
        public ProductsController(ApplicationContext _context)
        {
            Context = _context;
        }
        public IActionResult Index()
        {
            List<Product> AllProducts = Context.Products.Include(t => t.Tags).Include(p => p.Categories).ToList();
            // Fetch categories, tags
            List<Category> allCategories = Context.Categories.ToList(); // Assuming your categories are stored in a DbSet<Category>
            List<Tag> allTags = Context.Tags.ToList();


            ViewBag.Categories = allCategories;
            ViewBag.Tags = allTags;

            return View(AllProducts);

        }
        public IActionResult Details(int id)
        {
            Product CurrentProduct = new Product();
            CurrentProduct = Context.Products.Where(x => x.Id == id).FirstOrDefault();
            return View(CurrentProduct);
        }
        public IActionResult ProductsByCategory(int categoryId)
        {
            var productsInCategory = Context.Products.Where(p => p.Categories.Any(c => c.Id == categoryId)).ToList();
            List<Category> allCategories = Context.Categories.ToList();
            List<Tag> allTags = Context.Tags.ToList();


            ViewBag.Categories = allCategories;
            ViewBag.Tags = allTags;
            return View(productsInCategory);
        }

        public IActionResult ProductsByTag(int tagId)
        {
            var productsWithTag = Context.Products.Where(p => p.Tags.Any(t => t.Id == tagId)).ToList();
            List<Category> allCategories = Context.Categories.ToList(); // Assuming your categories are stored in a DbSet<Category>
            List<Tag> allTags = Context.Tags.ToList();


            ViewBag.Categories = allCategories;
            ViewBag.Tags = allTags;

            return View(productsWithTag);
        }


    }
}

Views/Shared/Cart.cshtml
<div id="cart-container">
    <div id="cart-title">
        Shopping cart
    </div>
</div>

Views/Shared/_AddToCartPopup.cshtml
<div id="cart-popup" style="display: none; position: fixed; top: 30%; left: 50%; transform: translate(-50%, -50%); background-color: #818B6E; color: #fff; border: 1px solid #ccc; padding: 40px; box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.5);">
    <p>Item added to cart</p>
</div>

<script>function addToCart(productId) {
        $.ajax({
            url: '/Carts/AddToCart/' + productId,
            type: 'POST',
            success: function () {
                // Show the popup
                $('#cart-popup').show();
                // Hide the popup after a few seconds
                setTimeout(function () {
                    $('#cart-popup').hide();
                }, 2000);
                // Update the cart icon
                updateCartIcon();
            },
            error: function (xhr, status, error) {
                console.error(error);
            }
        });
    }

    function updateCartIcon() {
        $.ajax({
            url: '/Carts/GetCartItemCount',
            type: 'GET',
            success: function (response) {
                // Update the cart icon with the number of items in the cart
                $('#cart-item-count').text(response);
            },
            error: function (xhr, status, error) {
                console.error(error);
            }
        });
        $(document).ready(function () {
            updateCartIcon();
        });
    }</script>

Views/Shared/_Cart.cshtml
<head>
    <link rel="stylesheet" href="~/css/product.css" />
</head>

<div>
    <div class="position-fixed top-0 end-0" style="padding: 10rem 7rem 5rem 2rem;">

        <a asp-controller="Carts" asp-action="Details">
            <button id="myButton" type="button" class="btn-cart">
                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="70" height="70" viewBox="0 0 256 256" xml:space="preserve">

<defs>
</defs>
<g style="stroke: none; stroke-width: 0; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: none; fill-rule: nonzero; opacity: 1;" transform="translate(1.4065934065934016 1.4065934065934016) scale(2.81 2.81)">
                <path d="M 72.975 58.994 H 31.855 c -1.539 0 -2.897 -1.005 -3.347 -2.477 L 15.199 13.006 H 3.5 c -1.933 0 -3.5 -1.567 -3.5 -3.5 s 1.567 -3.5 3.5 -3.5 h 14.289 c 1.539 0 2.897 1.005 3.347 2.476 l 13.309 43.512 h 36.204 l 10.585 -25.191 h -6.021 c -1.933 0 -3.5 -1.567 -3.5 -3.5 s 1.567 -3.5 3.5 -3.5 H 86.5 c 1.172 0 2.267 0.587 2.915 1.563 s 0.766 2.212 0.312 3.293 L 76.201 56.85 C 75.655 58.149 74.384 58.994 72.975 58.994 z" style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;" transform=" matrix(1 0 0 1 0 0) " stroke-linecap="round" />
                <circle cx="28.88" cy="74.33" r="6.16" style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;" transform="  matrix(1 0 0 1 0 0) " />
                <circle cx="74.59" cy="74.33" r="6.16" style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;" transform="  matrix(1 0 0 1 0 0) " />
                <path d="M 48.188 40.595 l -1.705 -0.951 c -3.698 -2.063 -9.26 -6.75 -11.669 -9.834 c -5.495 -7.033 -6.395 -15.264 -2.188 -20.017 c 2.061 -2.328 4.943 -3.67 8.117 -3.78 c 2.582 -0.084 5.153 0.659 7.445 2.142 c 2.293 -1.482 4.864 -2.235 7.446 -2.141 c 3.174 0.11 6.056 1.452 8.116 3.779 l 0 0 c 4.207 4.752 3.307 12.983 -2.188 20.018 c -2.409 3.083 -7.971 7.771 -11.669 9.833 L 48.188 40.595 z M 41.155 13.006 c -0.057 0 -0.113 0.001 -0.169 0.003 c -1.235 0.042 -2.342 0.548 -3.117 1.423 c -1.811 2.046 -0.707 7.011 2.462 11.068 c 1.519 1.944 5.046 5.025 7.858 6.957 c 2.813 -1.932 6.34 -5.013 7.858 -6.957 c 3.169 -4.057 4.273 -9.021 2.462 -11.068 l 0 0 c -0.774 -0.875 -1.881 -1.381 -3.116 -1.423 c -1.621 -0.053 -3.308 0.694 -4.75 2.111 l -2.454 2.414 l -2.455 -2.414 C 44.344 13.752 42.724 13.006 41.155 13.006 z" style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;" transform=" matrix(1 0 0 1 0 0) " stroke-linecap="round" />
</g>
</svg>
            </button>
        </a>
    </div>
</div>

Views/Shared/_Sidebar.cshtml
<div class="sidebar">


    <div class="sidebar-link">
        <h2>Our products</h2>
        <ul>
            <li><a class="a-sidebar" asp-controller="Products" asp-action="Index">All products</a></li>
        </ul>
    </div>
    <div class="sidebar-category">
        <h2>Category</h2>
        <ul>
            @foreach (var category in ViewBag.Categories)
            {
                <li><a class="a-sidebar" asp-controller="Products" asp-action="ProductsByCategory" asp-route-categoryId="@category.Id">@category.CategoryName</a></li>
            }
        </ul>
    </div>

    <div class="sidebar-tags">
        <h2>Tag</h2>
        <ul>
            @foreach (var tag in ViewBag.Tags)
            {
                <li><a class="a-sidebar" asp-controller="Products" asp-action="ProductsByTag" asp-route-tagId="@tag.Id">@tag.TagName</a></li>
            }
        </ul>
    </div>
</div>