Models/Cart.cs
using System;
namespace HarmonyHaven.Models
{
	public class Cart
	{   
            public int Id { get; set; }
            public decimal CartTotal { get; set; }
            public List<CartItem> CartItems { get; set; }
       
    }

}

Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HarmonyHaven.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HarmonyHaven.Controllers
{
    public class CartsController : Controller
    {
        private readonly ApplicationContext Context;

        public CartsController(ApplicationContext _context)
        {
            Context = _context;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult AddToCart(int id)
        {
            Product CurrentProduct = Context.Products.FirstOrDefault(x => x.Id == id);
            CartItem ExistingCartItem = Context.CartItems
                .FirstOrDefault(x => x.CartId == 1 && x.ProductId == CurrentProduct.Id);
            if (ExistingCartItem != null)
            {
                ExistingCartItem.Quantity = ExistingCartItem.Quantity + 1;
                ExistingCartItem.CartItemTotal = ExistingCartItem.CartItemTotal + CurrentProduct.ProductPrice;
                Context.CartItems.Update(ExistingCartItem);
                Cart Cart = Context.Carts.FirstOrDefault(x => x.Id == 1);
                Cart.CartTotal = Cart.CartTotal + CurrentProduct.ProductPrice;
                Context.SaveChanges();
            }
            else
            {
                CartItem CartItem = new CartItem();
                CartItem.ProductId = CurrentProduct.Id;
                CartItem.Quantity = 1;
                CartItem.CartItemTotal = CurrentProduct.ProductPrice;
                Cart Cart = Context.Carts.FirstOrDefault(x => x.Id == 1);
                Cart.CartTotal = Cart.CartTotal + CartItem.CartItemTotal;
                Cart.CartItems = new List<CartItem>();
                Cart.CartItems.Add(CartItem);
                Context.Carts.Update(Cart);
                Context.SaveChanges();
            }

            return RedirectToAction(nameof(Details));

        }
        public IActionResult AddOneItem(int id)
        {
            Cart ThisCart = Context.Carts.FirstOrDefault(x => x.Id == 1);
            Product CurrentProduct = Context.Products.FirstOrDefault(x => x.Id == id);
            CartItem CurrentCartItem = Context.CartItems
                .FirstOrDefault(x => x.CartId == 1 && x.ProductId == id);

            CurrentCartItem.Quantity = CurrentCartItem.Quantity + 1;
            CurrentCartItem.CartItemTotal = CurrentCartItem.CartItemTotal + CurrentProduct.ProductPrice;
            Context.CartItems.Update(CurrentCartItem);
            ThisCart.CartTotal = ThisCart.CartTotal + CurrentProduct.ProductPrice;
            Context.Carts.Update(ThisCart);
            Context.SaveChanges();

            return RedirectToAction(nameof(Details));

        }

        public IActionResult RemoveOneItem(int id)

        {

            Cart ThisCart = Context.Carts.FirstOrDefault(x => x.Id == 1);
            Product CurrentProduct = Context.Products.FirstOrDefault(x => x.Id == id);
            CartItem CurrentCartItem = Context.CartItems
                .FirstOrDefault(x => x.CartId == 1 && x.ProductId == id);


            if (CurrentCartItem != null)
            {
                if (CurrentCartItem.Quantity > 1)

                {
                    CurrentCartItem.Quantity = CurrentCartItem.Quantity - 1;
                    CurrentCartItem.CartItemTotal = CurrentCartItem.CartItemTotal - CurrentProduct.ProductPrice;
                    Context.CartItems.Update(CurrentCartItem);
                    ThisCart.CartTotal = ThisCart.CartTotal - CurrentProduct.ProductPrice;
                    Context.Carts.Update(ThisCart);
                    Context.SaveChanges();
                }

                else if (CurrentCartItem.Quantity <= 1)

                {
                    CurrentCartItem.Quantity = 0;
                    Context.CartItems.Remove(CurrentCartItem);
                    ThisCart.CartTotal = ThisCart.CartTotal - CurrentProduct.ProductPrice;
                    Context.Carts.Update(ThisCart);
                    Context.SaveChanges();
                }
            }

            return RedirectToAction(nameof(Details));
        }
        public IActionResult RemoveAllOfTheseItems(int id)
        {

            Cart ThisCart = Context.Carts.FirstOrDefault(x => x.Id == 1);
            Product CurrentProduct = Context.Products.FirstOrDefault(x => x.Id == id);
            CartItem CurrentCartItem = Context.CartItems
                .FirstOrDefault(x => x.CartId == 1 && x.ProductId == id);
            List<CartItem> AllOfTheseItems = Context.CartItems.ToList();

            foreach (CartItem item in AllOfTheseItems.Where(x => x.ProductId == id))

            {
                ThisCart.CartTotal = ThisCart.CartTotal - (CurrentProduct.ProductPrice * CurrentCartItem.Quantity);
                CurrentCartItem.Quantity = CurrentCartItem.Quantity - 1;
                Context.CartItems.Remove(item);
                Context.Carts.Update(ThisCart);
            }
            Context.SaveChanges();
            return RedirectToAction(nameof(Details));
        }

        public IActionResult EmptyCart(int id)
        {
            List<CartItem> CurrentCartItem = Context.CartItems
                .Where(x => x.Id >= 1).ToList();
            Context.CartItems.RemoveRange(CurrentCartItem);

            Cart ThisCart = Context.Carts.FirstOrDefault(x => x.Id == 1);
            ThisCart.CartTotal = 0;
            Context.Carts.Update(ThisCart);
            Context.SaveChanges();
            return RedirectToAction(nameof(Details));
        }
        public IActionResult Details()
        {
            Cart Cart = Context.Carts
                .Include(ci => ci.CartItems).ThenInclude(p => p.Product).FirstOrDefault(x => x.Id == 1);
            return View(Cart);
        }


        public IActionResult DetailsSek()
        {
            Cart Cart = Context.Carts
                .Include(ci => ci.CartItems).ThenInclude(p => p.Product).FirstOrDefault(x => x.Id == 1);

            foreach (CartItem cartItem in Cart.CartItems)
            {
                cartItem.CartItemTotal /= 10;
            }
            Cart.CartTotal /= 10;


            return View(Cart);
        }

    }
}

Controllers/CheckoutsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using HarmonyHaven.Models;
using Microsoft.AspNetCore.Mvc;

namespace HarmonyHaven.Controllers
{
    public class CheckoutsController : Controller
    {
        private readonly ApplicationContext Context;
        public CheckoutsController(ApplicationContext context)
        {
            Context = context;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Details()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Details(string Fullname, string Email,
            int PhoneNumber, string Country, string City,
            string Address, int ZipCode, string CardHoldersName, int CardNumber,
            string CardExpiryDate, int CVC)
        {
            Checkout NewCheckout = new Checkout();
            if (NewCheckout == null)
            {
                NewCheckout.Fullname = Fullname;
                NewCheckout.Email = Email;
                NewCheckout.PhoneNumber = PhoneNumber;
                NewCheckout.Country = Country;
                NewCheckout.City = City;
                NewCheckout.Address = Address;
                NewCheckout.ZipCode = ZipCode;
                NewCheckout.CardHoldersName = CardHoldersName;
                NewCheckout.CardNumber = CardNumber;
                NewCheckout.CardExpiryDate = CardExpiryDate;
                NewCheckout.CVC = CVC;
                Context.Update(NewCheckout);
                Context.Checkouts.Add(NewCheckout);
                Context.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }

        public string MyCheckout()
        {
            return "Checkout with your shopping cart products.";
        }

    }
}

Views/Carts/Details.cshtml
@model HarmonyHaven.Models.Cart
<head>
    <link rel="stylesheet" href="/css/product.css" />

</head>


    <div class="sectionmini_product">

    </div>
    <div class="container shop-cart">
        <h1 class="h1-shop">SHOPPING CART</h1>

        @if (Model.CartItems.Count() != 0)
        {
            <table class="table">
                <thead>
                    <tr>
                        <th>Product Name</th>
                        <th>Quantity</th>
                        <th>Price</th>
                        <th>Subtotal</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (CartItem Item in Model.CartItems)
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => Item.Product.ProductName)</td>
                            <td>@Html.DisplayFor(modelItem => Item.Quantity)</td>
                            <td>@Html.DisplayFor(modelItem => Item.Product.ProductPrice)</td>
                            <td>@Html.DisplayFor(modelItem => Item.CartItemTotal)</td>
                            <td>
                                <a class="btn btn-sm btn-success" asp-controller="Carts" asp-action="RemoveOneItem" asp-route-id="@Item.ProductId">-</a>
                                <a class="btn btn-sm btn-success" asp-controller="Carts" asp-action="AddOneItem" asp-route-id="@Item.ProductId">+</a>
                                <a class="btn btn-sm btn-danger" asp-controller="Carts" asp-action="RemoveAllOfTheseItems" asp-route-id="@Item.ProductId">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z" />
                                        <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z" />
                                    </svg>
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <hr />
            <div class="checkout">


                <span>Total: $</span>@Html.DisplayFor(model => model.CartTotal)
                <br />
                <a asp-controller="Checkouts" asp-action="Details" class="btn btn-sm btn-success">Order checkout</a>
                <br />
                <a asp-controller="Carts" asp-action="EmptyCart">
                    <button type="button" class="btn btn-sm btn-danger mt-1">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z" />
                            <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z" />
                        </svg>
                        Empty cart
                    </button>
                </a>
            </div>
                }
                else
                {
                <h3 class="text-warning">Your cart is empty</h3>
                }
           
    </div>

Views/Carts/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}